version: 2

updates:
  - package-ecosystem: uv
    directory: /convert-attestations
    groups:
      python:
        patterns:
          - "*"
    schedule:
      interval: daily
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: /
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      interval: daily
    cooldown:
      default-days: 7
