name: 'adapt-sigstore-pypi'
description: 'Convert Sigstore bundles to PyPI attestations'
inputs:
  bundles:
    description: >-
      Sigstore bundles to convert. Accepts only .jsonl files.
      May contain a glob pattern or list of paths.
    required: true
  output-dir:
    description: >-
      Directory where to store the converted attestations.
      Optional, if omitted a new temporary directory will be
      created and returned as an output.
    required: false
outputs:
  output-dir:
    description: 'Directory containing the converted PyPI attestations'
runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "0.5.6"
    - name: Convert attestations
      shell: bash
      run: |
        uv install ${{ github.action_path }}/convert-attestations/
        uv run convert-attestations
          ${{ inputs.output-dir != '' && format('--output-dir {0}', inputs.output-dir) || '' }} \
          ${{ inputs.bundles }}
