name: 'adapt-sigstore-pypi'
description: 'Convert Sigstore bundles to PyPI attestations'
inputs:
  bundles:
    description: >-
      Sigstore bundles to convert. Accepts only .jsonl files.
      May contain a glob pattern or list of paths.
    required: true
outputs:
  output-dir:
    description: 'Directory containing the converted PyPI attestations'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/astral-sh/uv:0.5-python3.13-bookworm-slim'
  args:
    - uv
    - run
    - --prerelease=allow
    - convert-attestations.py
    - ${{ inputs.bundles }}
