name: Integration tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-github-action:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # to sign the provenance
      attestations: write # to persist the attestation files
    steps:
      - name: Checkout action repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Create artifacts
        run: mkdir dist && echo "a" > dist/artifact1.txt && echo "b" > dist/artifact2.txt
      - name: Create provenances
        id: create-provenances
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'dist/*'
      - name: Convert provenances
        uses: ./
        with:
          bundles: ${{ steps.create-provenances.outputs.bundle-path }}
          output-dir: dist/
      - name: List dist/ contents
        run: ls dist
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      - name: Install pypi-attestations tool
        run: uv tool install --prerelease=allow pypi-attestations==0.0.21
      - name: Check provenances
        run: pypi-attestations verify attestation --identity "aa" dist/artifact1.txt dist/artifact2.txt

